### ISSUE TITLE
Is LUI available somewhere?

### ISSUE THREAD

**Issue by trusktr** [heremaps/xyz-editor#15]
This is a little bit unrelated to this repo, but I noticed a neat UI framework being used on https://xyz.api.here.com/token-ui/, called "LUI", and I see custom elements in the page named with the prefix `lui-`.

The UI looks very nice!

I was wondering if this UI kit is available anywhere? If not, are there any plans to open-source it? 

As an experiment, I was able to place the script `https://xyz.api.here.com/token-ui/js/lui-all.min.js` onto my own page, and play with some components, but this comes with no documentation (and may be of questionable legality).

The LUI framework looks very interesting. It'd be neat to use it!

**Comment by tsteenbe** [comment]
Hi @trusktr, I am the Head of Open Source for HERE Technologies - I can tell you that are ongoing discussions regarding open-sourcing our LUI framework but it may take a while. Apart from getting the code ready for being open-sourced the framework also contains a lot of map-related icons so we need to check if we can open-source these as well.
