### ISSUE TITLE
Icons on the road do not rotate with view

### ISSUE THREAD

**Issue by HERE-TK** [heremaps/xyz-editor#40]
[ViewRotateIconsOnRoadsBug.zip](https://github.com/heremaps/xyz-editor/files/5223541/ViewRotateIconsOnRoadsBug.zip)
When rotating the map, the icons on roads like directions and oneway arrows stay the same direction canvas wise. They should rotate with the road of course.
![direction0](https://user-images.githubusercontent.com/67630072/93185081-4cb1ae00-f73d-11ea-96f3-364183288d85.png)
![direction1](https://user-images.githubusercontent.com/67630072/93185087-4d4a4480-f73d-11ea-8a74-532d2a93de8a.png)

**Comment by TerminalTim** [comment]
if icon alignment (pitch) ist set to "viewport" the rotation is aligning to "viewport" as well.
For this use case it makes sense to introduce "rotationAlignment" property to allow individual control about rotation behavior and decouple from pitch alignment.

A quick fix is to set icon alignment to "map" for now.
