### ISSUE TITLE
Polygon outline does not render correctly.

### ISSUE THREAD

**Issue by asitvachhani** [heremaps/xyz-editor#42]
In the case of MultiPolygon, some of the outlines of Polygon does not render as expected.
[XYZChairsRendering.zip](https://github.com/heremaps/xyz-editor/files/5486973/XYZChairsRendering.zip)

**Comment by TerminalTim** [comment]
could you please give more detail about the issue and provide a simple html with isolated problem to reproduce?

**Comment by asitvachhani** [comment]
Hi Tim,

Please look at the attached HTML which can be run on [XYZ Map Playgorund](https://xyz.api.here.com/maps/latest/playground/index.html#core_Building%20Add%20and%20Remove). 

If you click on the "Add building" button, it will draw two polygons from a MultiPolygon feature. The first polygon has 5 Points (simple rectangle shape). Now if you look at the rendered polygon, you will see that polygon is rendered correctly which is in blue but, the outline of the polygon does not seem right. It generates a triangle shape and one line is drawn diagonally. 

At the same time, another polygon renders correctly as expected with color and outline both. This is what we expect for the first Polygon as well. Both should render the correct rectangle shape.
<img width="468" alt="PolygonOutlineResult" src="https://user-images.githubusercontent.com/1752127/98103818-986e1180-1ebb-11eb-9550-ba9dad679689.png">


[PolygonOutlineIssue.html.zip](https://github.com/heremaps/xyz-editor/files/5487332/PolygonOutlineIssue.html.zip)

**Comment by TerminalTim** [comment]
thanks. i can reproduce the issue. 
It looks like the error only occurs for very tiny geometry in centimeter range.
